Home: Add card with reference to "All Features" page
crate/cratedb-guide pull request #131
Opened 2024-11-13 22:16 UTC by amotl

## About
@kneth signalled interest to increase awareness about the [All Features](https://cratedb.com/docs/guide/feature/) page.
This patch intends to add a reference to the [Docs Home](https://cratedb.com/docs/guide/home/) page.

## Preview
_Rendering._

2024-11-14 06:38 UTC, proddata commented
I am not sure we should really deemphasize the Reference Manual. Also, this isn’t new, but the title “All Features” seems a bit unspecific about what it actually contains. Since it’s located in Guides and Tutorials, does that mean it consists of guides and tutorials? If so, we already have multiple links to guides and tutorials there anyway. Could you elaborate on how the “All Features” page is meant to be used and in what part of the user journey?

2024-11-14 11:21 UTC, proddata requested changes
There are already multiple links to “Guides and Tutorials” on the homepage, so adding another might be redundant and could draw attention away from the Reference Manual.

Additionally, labeling this section “All Features” is potentially misleading, as it doesn’t include features specific to CrateDB as a managed service.

2024-11-14 11:37 UTC, amotl commented
> Additionally, labeling this section “All Features” is potentially misleading, as it doesn’t include features specific to CrateDB as a managed service.

We will be happy to improve the situation on the “All Features” page as we go, by also indexing relevant features of CrateDB Cloud in a similar style, when applicable.

> There are already multiple links to “Guides and Tutorials” on the homepage, so adding another might be redundant and could draw attention away from the Reference Manual.

I think this is not likely, specifically because it is also prominently referenced in the primary navigation.

2024-11-15 08:58 UTC, kneth commented
> deemphasize the Reference Manual

To me, it is more about emphasizing features and how to get started. I don't expect a data scientist or software engineer to read the reference manual first.

2024-11-15 14:11 UTC, amotl commented
>> Additionally, labeling this section “All Features” is potentially misleading, as it doesn’t include features specific to CrateDB as a managed service.
>
> We will be happy to improve the situation on the “All Features” page as we go, by also indexing relevant features of CrateDB Cloud in a similar style, when applicable.

Hi. I've just broken this out to be separate.

- GH-137

2024-11-15 18:23 UTC, amotl reviewed
Hi. We are going to merge this patch, but we will be happy to accept and apply improvement suggestions also in retrospective, any time.

Please also contribute patches to progressively support shaping the documentation as it should be, reflecting your dearest wishes. Thanks!

2024-11-15 18:27 UTC, merged